image: elixir:1.7.4

services:
  - postgres:9.6

variables:
  POSTGRES_DB: prison_rideshare_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

cache:
  paths:
    - deps/
    - _build/

stages:
  - test
  - deploy

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test

mix:
  stage: test
  script:
  - mix coveralls.post --branch $CI_COMMIT_REF_NAME --sha $CI_COMMIT_SHORT_SHA --message "$CI_COMMIT_MESSAGE"

deploy:
  stage: deploy
  only:
    - primary
  script: .ci/deploy-sandbox.sh