image: elixir:1.6.0

services:
  - postgres:9.6

variables:
  POSTGRES_DB: prison_rideshare_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get --only test
  # FIXME Creates an expected file excluded by .gitignore
  - "echo 'use Mix.Config\n\nconfig :prison_rideshare, nothing: 0' > config/dev.secret.exs"

mix:
  script:
  - mix test