language: elixir
elixir:
  - 1.5.1
dist: trusty

addons:
  postgresql: 9.6

cache:
  directories:
    - _build
    - deps

env:
  - MIX_ENV=test

before_install:
  # FIXME Creates an expected file excluded by .gitignore
  - "echo 'use Mix.Config\n\nconfig :prison_rideshare, nothing: 0' > config/dev.secret.exs"

#script: mix coveralls.travis
script: echo "hey"

after_success:
  - openssl aes-256-cbc -K $encrypted_efc605b46718_key -iv $encrypted_efc605b46718_iv -in .travis/deploy.key.enc -out .travis/deploy.key -d
  - chmod 600 .travis/deploy.key # this key should have push access

  - eval "$(ssh-agent -s)" #start the ssh agent
  - ssh-add .travis/deploy.key
  - ssh-keyscan corepoint.chromatin.ca >> ~/.ssh/known_hosts

  - git remote add deploy dokku@corepoint.chromatin.ca:prison-rideshare-api-sandbox
  - git config --global push.default simple
  - git push deploy dokku-sandbox:primary

  - ssh -t dokku@corepoint.chromatin.ca -- run prison-rideshare-api-sandbox mix reset_sandbox
