language: elixir
elixir:
  - 1.4.2

before_install:
  # FIXME Creates an expected file excluded by .gitignore
  - "echo 'use Mix.Config\n\nconfig :prison_rideshare, nothing: 0' > config/dev.secret.exs"

deploy:
  provider: heroku
  api_key:
    secure: v4xSHkW7oroJoD7WV3AP52+QwElTd/rZ3hDKSOTyK0+9zbM3m7RokXOM+Cla8OMNQclQ8ikYcAHOQpBbRWuoo4cNHMaxbLCe6mGvd3ixb1ADvEmoJZXcJYrOZx7Yo6zFra3kL1BZXsUKRefeevxg9fjjXq2kw0B9ib1n5bNgrYYmXBkDAYUs67wwD9ljySvOP/N2b8jfIEdl7a0cV7WEOPXHxmqoQ8YWiciszi6S+GGclcQGGSYdXJ//d8xxuP29oXlfK0HdnTjhfaDbTER4ARel4Ic0ndfMa0VKsslDdyACbH6knYrr0W8oonznbYbOu4KM90xRx8hv7co9qWUFvVdlvQTAx1TVB/kWIkLLBYgFtOZD6Ok95t5kY77jeB+f2xGD2QWB1QBkW8smA+doToBzIWrP5vxWVRK8oiWWvDRHSTC5rjeqZNx/IYaSI4d68Xu5BohIXfgOIPeaDo1zn+XV51HM5GJPPPljJ6o2V47NMmMq4pl0URfW16gbmXo3RLTm4hJ53h7t0Ds/RvHYc8xHRM0rPqQXno4GoON1sikr/jM7n4LPY8tONSxnkyYFulGImv4miLAmO7waGvPIey2c47LhmSNE5pLcr0hH4DIDX6fsGnXI0VK8P88BgPu9FU8Uabr+PFTnfpDN23Qux/FbKUoK5whBy5Wa3BYRnpE=
  app: prison-rideshare-api-sandbox
  on:
    repo: backspace/prison-rideshare-api
    branch: primary
